[package]
name = "apfs"
version = "0.1.0"
authors = ["Loren M. Lang <lorenl@north-winds.org>"]
edition = "2018"

[dependencies]
bitflags = "1.2.1"
byteorder = "1.3.1"
num-derive = "0.3.2"
num-traits = "0.2.12"
uuid = "0.8.1"

[features]
expensive_tests = []